@startuml
'https://plantuml.com/activity-diagram-beta

start

: Окно главной страницы;

switch ( Выбор действия )
case ( Пройти тест )
  :Окно с вопросами;
  :Выбор вариантов;
  :Подсчет результатов;
  :Окно результата теста;
case ( Выбрать профили )
  :Окно выбора профилей;
  :Выбор профилей;
case ( Выбрать предметы )
  :Окно выбора предметов;
  :Выбор предметов;

endswitch


:Подбор рекомендуемого ВУЗа;
:Вывод рекомендации;


end
@enduml
