@startuml
'https://plantuml.com/use-case-diagram

Пользователь -> (Получить рекомендацию\nпо университетам)
(Получить рекомендацию\nпо университетам) ..> (Пройти тест): <<include>>
(Получить рекомендацию\nпо университетам) ..> (Выбрать профили): <<include>>
(Получить рекомендацию\nпо университетам) ..> (Выбрать предметы): <<include>>

(Выбрать профили) <.. (Получить соответствие\nпрофилей и предметов): <<include>>
(Выбрать предметы) <.. (Получить соответствие\nпрофилей и предметов): <<include>>
Пользователь -> (Получить соответствие\nпрофилей и предметов)

@enduml